### PR TITLE
would like to run flipcss.clean

### PR DESCRIPTION
**Pull request by lewie6**
see lines 22 and 45

i need to run flipcss.clean, think it would make a nice option?

i think most people would want to run flipcss.clean by default (hence line 22)... but we could take that out if you think it should not be there by default

### CODE REVIEW

**Comment by behrang** [comment]
Please consider backwards compatibility. With this change, we might break users who just upgrade to this version. I would set default value as null or false to prevent any accidental activation of this behaviour. 

Also, please check travis report. I didn't check it but it is failed. It may be because of your change, or it may be old node version config in travis configuration.

Also, please add a few test cases to test expected behaviour with or without this configuration.

Thanks

**Comment by lewie6** [comment]
yeah, tests failing because the flipcss.clean is run by default. 
ive made it not run by default... should pass now
this will also be ok for backwards compatibility 
added some basic tests, but not sure exactly what all the flipcss.clean does so just a basic thing for now

need to add files before the tests will work

**Comment by behrang** [comment]
Ok, it's good. Please add those test fixture and expectation to this pull request, and if you can add a guide line to Readme.md so other users will know about this feature. Thank you.

**Comment by lewie6** [comment]
hey, added all that to this pull request. hope that is ok

thanks for your help/input

**Comment by behrang** [comment]
Great. Thanks for your contribution.

**Comment by behrang** [comment]
It's available in version 0.4.0.

**Pull request merged**
